WIDTH, HEIGHT = 600, 600
GAME_SIZE_MULTIPLIER = 4
FPS = 60
STAR_DENSITY = 0.0002

PLAYER_SPEED = 5
PLAYER_ROTATE_SPEED = 5
PLAYER_HEIGHT = 28
PLAYER_WIDTH = 28

ASTEROID_DENSITY = 0.00001
ASTEROID_WIN_COUNT = 20
ASTEROID_HEIGHT = 24
ASTEROID_WIDTH = 24

TIME_LIMIT = 30  # in seconds

# Game space dimensions
GAME_WIDTH, GAME_HEIGHT = WIDTH * GAME_SIZE_MULTIPLIER, HEIGHT * GAME_SIZE_MULTIPLIER
ASTEROID_COUNT = int(GAME_WIDTH * GAME_HEIGHT * ASTEROID_DENSITY)