GAMESPACE_WIDTH, GAMESPACE_HEIGHT = 600, 600
GAME_SIZE_MULTIPLIER = 4
ASTEROID_DENSITY = 0.00001

GAME_WIDTH = GAMESPACE_WIDTH * GAME_SIZE_MULTIPLIER
GAME_HEIGHT = GAMESPACE_HEIGHT * GAME_SIZE_MULTIPLIER

ASTEROID_COUNT = int(GAME_WIDTH * GAME_HEIGHT * ASTEROID_DENSITY)